uncscode/particula

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, README.md, requirements.txt
- .devcontainer/ has json details of settings and extensions as well as dockerfile
- linting and minor edits of readme
- added pandas to requirements
=> adding devcontainer

docs/index.html
adding docs/index.html as placeholder for webpage
=> placeholder for webpage / fixes #9 

README.md
I added a link to the Google style guide. 
Fixes #14
=> Test issue to practice contribution workflow

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, aerosol_dynamics/__init__.py, aerosol_dynamics/particle.py, aerosol_dynamics/particle_test.py, aerosol_dynamics/physical_parameters.py, requirements.txt
Added decorators to functions to conduct units checking.
Added docstrings to many (but not all) functions.
Added vsliveshare extension so we can hold pair programming/audio chat sessions.
Co-authored-by: aktwo <aktwo@users.noreply.github.com>
=> Improved Particle class & methods, typing & units. 

.github/workflows/python-package.yml, .gitignore, aerosol_dynamics/__init__.py, aerosol_dynamics/particle.py, aerosol_dynamics/particle_test.py, aerosol_dynamics/physical_parameters.py
=> fixing workflow tests

aerosol_dynamics/environment.py, aerosol_dynamics/environment_test.py, aerosol_dynamics/particle.py, aerosol_dynamics/particle_test.py, aerosol_dynamics/physical_parameters.py
Creates an Environment class to set the properties of an air parcel, such as temperature and pressure.
Fixes #30
=> Create an Environment Class 

.github/workflows/jupyter-book.yml, docs/intro.md
=> bugfix for jupyterbook build

aerosol_dynamics/parcel.py, aerosol_dynamics/parcel_test.py
=> first draft: air parcel for managing particles

.github/workflows/CODEOWNERS, .github/workflows/jupyter-book.yml, .github/workflows/python-package-flake8.yml, .github/workflows/python-package-pylint.yml, .github/workflows/python-package-pytest.yml, .github/workflows/python-publish.yml, particula/aerosol_dynamics/particle_test.py
Fixes #54
Highlights:
- added codeowners (for now everywhere, more granual later)
- split linters
- better titles of workflows
- make flake8 fail if errors
- removed manyversions from linters
Notes (if applicable):
- n/a
=> improving github action workflows 

docs/CONTRIBUTING.md, docs/getting_started.ipynb, docs/tutorials/001_ParticleClass.ipynb
=> docs post-v0.0.3

particula/aerosol_dynamics/tests/particle_test.py
Fixes #86
Goes directly into branch wkchuang/issue82 and should be merged before #84
=> Fixing UnitStrippedWarning

particula/aerosol_dynamics/parcel.py, particula/aerosol_dynamics/tests/parcel_test.py
=> added particle coagulation in parcel class

.devcontainer/devcontainer.json, setup.cfg
Fixes #
Highlights:
- this installs particula as a package upon creating the container
- make editing and dev work easier
- symlinked to site-packages, and thus edits are immediate
Notes (if applicable):
- no need to play with paths ever again
- more documentation to follow
-
=> make an editable install of particula in devcontainer

.devcontainer/devcontainer.json, particula/__init__.py, setup.cfg
Follows and builds on #96
Closes #96
Highlights:
- better versioning in `particula/__init__.py`
- make setup.cfg read attr
- add dev0 (dev1, dev2, etc.) for dev builds
Notes (if applicable):
- n/a
-
=> packaging particula with better versioning

requirements.txt, setup.cfg
Fixes #111
No changes, just adding flake8 to dev reqs (somehow it was missing, sorry)
=> add flake8 to requirements.txt

.github/workflows/stale.yml
=> adding stale bot

.github/workflows/python-package-pytype.yml, particula/aerosol_dynamics/parcel.py, setup.cfg
Fixes #3 
- adding pytype analysis
- fixed issues in parcel (remove types at outputs for now)
- part of ci from now on
=> adding pytype analysis

particula/util/particle_mass.py, particula/util/reduced_quantity.py, particula/util/tests/particle_mass_test.py, particula/util/tests/reduced_quantity_test.py
- simple mass calc, ensuring arrays work + test
- generic reduced_quantity function + test
=> adding particle mass and reduced mass utils

particula/__init__.py
bumping ver no in anticipation of updating the aerosol_dynamics modules
=> bump version number: 0.0.4.dev0 --> 0.0.4.dev1

particula/__init__.py, particula/aerosol_dynamics/particle_distribution.py
=> fixing logspace

particula/aerosol_dynamics/tests/particle_distribution_test.py
=> improve testing for logspace stuff

particula/util/coagulation_rate.py
=> more flexible coag rate calc

docs/_toc.yml, docs/documentation/environment.ipynb
=> document environment.py

docs/_toc.yml, docs/documentation/vapor.ipynb
=> document vapor.py

particula/__init__.py
=> release 0.0.4

particula/particle.py, particula/tests/particle_test.py, particula/util/distribution_discretization.py, particula/util/radius_cutoff.py, particula/util/tests/distribution_discretization_test.py, particula/util/tests/radius_cutoff_test.py
=> fix radius_cutoff

particula/__init__.py, particula/particle.py, particula/tests/particle_test.py
Fixes #210
Fixes #
Highlights:
- make sure input nbins is flexible
- add tests
-
Notes (if applicable):
- pretty minimal PR
-
=> fix treatment of nbins

docs/_toc.yml, docs/examples/loading_data_part1.ipynb, docs/examples/loading_data_part2.ipynb
=> link to example part 2

docs/examples/loading_data_part1.ipynb, docs/examples/loading_data_part2.ipynb
=> fixing loader example for real

particula/data/processer.py
=> fix some of the old references datalake and datastream

particula/data/lake.py, particula/data/stream_stats.py, particula/data/tests/lake_test.py
=>  the lake class

docs/_toc.yml, docs/examples/activity_part1.ipynb
=> book link fix

particula/data/loader.py, particula/data/process/size_distribution.py, particula/data/stream.py, particula/data/stream_stats.py
Bug, fix for the behavior when exporting data streams and filters.
=> Data export revision
